require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*' 
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'spec/**/*'
Metrics/LineLength:
  Max: 150
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*
  Max: 20
Metrics/MethodLength:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/ClassLength:
  Max: 220
Metrics/AbcSize:
  Max: 75
Metrics/PerceivedComplexity:
  Max: 20
Style/Documentation:
  Enabled: false
Layout/IndentationWidth:
  Width: 2
Naming/ClassAndModuleCamelCase:
  Enabled: true
Naming/MethodName:
  Enabled: true
  EnforcedStyle: snake_case #default