language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
script:
- rvm install 'ruby-2.7.2'
- rvm use 'ruby-2.7.2'
- bundle install --jobs=3 --retry=3
- yarn install
- bin/webpack
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rspec
dist: xenial
addons:
  chrome: stable
before_install:
- # start your web application and listen on `localhost`
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
