name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7.2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.0

    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: JS package cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        yarn install --pure-lockfile

    - name: Build
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        REDIS_URL: redis://localhost:6379/0
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      run: | 
        sudo apt-get -yqq install libpq-dev
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:seed

  tests:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7.2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.19.0

    - name: Find yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: JS package cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages
      run: |
        yarn install --pure-lockfile

    - name: Build
      env:
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        REDIS_URL: redis://localhost:6379/0
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      run: | 
        sudo apt-get -yqq install libpq-dev
        bundle exec rake db:create
        bundle exec rake db:migrate
        bundle exec rake db:seed
        bundle exec rspec spec/feature/event_spec.rb -fd
